[workspace]
name = "flox"
version = "0.1.0"
description = "Single-file Flox documentation builder"
authors = ["Kolen Cheung <christian.kolen@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[tasks]

[dependencies]
beautifulsoup4 = ">=4.12,<5"
nodejs = ">=22,<25"
pandoc = "*"
python = "3.11.*"
