[project]
name = "nersc"
version = "0.1.0"
description = "Add a short description here"
authors = ["Kolen Cheung <christian.kolen@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "*"
defopt = "*"
pandoc = "*"
# modified from git/requirements.txt
mkdocs = "1.5.*"
mkdocs-material = "9.*"

[pypi-dependencies]
mkdocs-minify-plugin = "*"
mkdocs-meta-descriptions-plugin = "*"
mkdocs-print-site-plugin = "*"
mkdocs-exclude-search = "*"
mkdocs-redirects = "*"
